apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o7466sw23-go 
  janus-idp.io/tekton: o7466sw23-go
  backstage.io/kubernetes-id: o7466sw23-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7466sw23-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  